"""changing the created_at & updated_at

Revision ID: 9159b89768e3
Revises: 8586df9fd199
Create Date: 2024-09-15 23:05:27.683211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9159b89768e3'
down_revision: Union[str, None] = '8586df9fd199'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True))
    op.drop_column('books', 'update_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('update_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('books', 'updated_at')
    # ### end Alembic commands ###
